apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  labels:
    app: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.inputs }}
  input_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}

{{- range $key, $value := .Values.filters }}
  filter_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}

{{- range $key, $value := .Values.outputs }}
  output_{{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
