{
 "title": "ElasticSearch",
 "description": "ElasticSearch cluster stats",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Сluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "name",
    "label": "Node name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},name)"
    }
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Main Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1)+22"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "gauge",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "gauge",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1- (sum (elasticsearch_filesystem_data_free_bytes{cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"}))) *100"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} "
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active primary shards",
     "type": "stat",
     "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
     "repeat": "shard_type",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Active shards",
     "type": "stat",
     "description": "Aggregate total of all shards across all indices, which includes replica shards",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Initializing shards",
     "type": "singlestat",
     "description": "Count of shards that are being freshly created",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Relocating shards",
     "type": "singlestat",
     "description": "The number of shards that are currently moving from one node to another node.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Delayed shards",
     "type": "singlestat",
     "description": "Shards delayed to reduce reallocation overhead",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"} "
      }
     ]
    },
    {
     "title": "Unassigned shards",
     "type": "singlestat",
     "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "JVM & CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count",
     "type": "graph",
     "description": "Count of JVM GC runs",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "GCs" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}} "
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "description": "GC run time in seconds\n",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}} - {{gc}}"
      }
     ]
    },
    {
     "title": "JVM memory committed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_committed_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}} committed: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}} max: {{area}}"
      }
     ]
    },
    {
     "title": "JVM memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}} used: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}} max: {{area}}"
      },
      {
       "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}} peak used pool: {{pool}}"
      }
     ]
    },
    {
     "title": "Load average",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_os_load1{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "load1: {{name}}"
      },
      {
       "expr": "elasticsearch_os_load5{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "load5: {{name}}"
      },
      {
       "expr": "elasticsearch_os_load15{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "load15: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "Disk Usage %" }
     ],
     "targets": [
      {
       "expr": "1-(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}: {{path}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/sec" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_transport_tx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: sent"
      },
      {
       "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: recieve"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of documents with only primary shards",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_docs_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Documents count on node",
     "type": "graph",
     "gridPos": { "h": 5, "w": 14, "x": 10, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with only primary shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Documents merged bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Doc values with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Documents deleted rate",
     "type": "graph",
     "description": "Count of deleted documents on this node",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Doc values with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with all shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Documents merged rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents indexed rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short", "label": "index calls/s" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Indexing time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Throttle time for index store",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Merging time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Operations  rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "rate(elasticsearch_indices_refresh_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "rate(elasticsearch_indices_flush_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "rate(elasticsearch_indices_get_exists_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "rate(elasticsearch_indices_get_missing_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "rate(elasticsearch_indices_get_tota{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get"
      },
      {
       "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: indexing_delete"
      }
     ]
    },
    {
     "title": "Total Operations time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: indexing"
      },
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: query"
      },
      {
       "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: fetch"
      },
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "irate(elasticsearch_indices_get_exists_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get_time"
      },
      {
       "expr": "irate(elasticsearch_indices_get_missing_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: indexing_delete"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: get"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field data memory size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Evictions from filter cache",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_filter_cache_evictions{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations rejected",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_thread_pool_rejected_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations queued",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_thread_pool_active_count{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_thread_pool_active_count{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_thread_pool_completed_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total translog operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_operations{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total translog size in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_size_in_bytes{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of index segments",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current memory size of segments in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_memory_bytes{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Index writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index writer with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Index writer with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments with only primary shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_count_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments with all shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_count_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fields",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of fields with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fields_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of fields with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Fixed bit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size of fixed bit with only primary shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_primary{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of fixed bit with all shards on all nodes in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=~\"$instance\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}