{{- if .Values.licence.enabled }}
apiVersion: v1
data:
  keycloak-ca.pem: {{ .Values.Secrets.keycloak.certificate }}
kind: Secret
metadata:
  name: {{ .Values.Secrets.keycloak.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
