{{- if .Values.licence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Secrets.oidc.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  xpack.security.authc.realms.oidc.NSC.rp.client_secret: {{ .Values.Secrets.oidc.data.rp_client_secret | b64enc | quote }}
{{- end }}
