apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-test
spec:
  type: filebeat
  version: 7.14.0
  config:
    filebeat.inputs:
    - type: log
      paths:
      - /var/log/logstash/sample.log
    output.logstash:
      hosts: ["IP:PORT"]
  daemonSet:
    podTemplate:
      spec:
    #    nodeName: kid2comp003
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          - name: logstash
            mountPath: /var/log/logstash
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: logstash
          hostPath:
            path: /var/log/logstash
